app = 'pan-api'
primary_region = 'syd'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[mounts]
  source = 'pan_uploads'
  destination = '/app/uploads'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
